# Generated by Django 6.0.1 on 2026-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='deficiency',
            field=models.CharField(default='Not calculated', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='healthy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='streak',
            field=models.IntegerField(),
        ),
    ]
