# Generated by Django 6.0.1 on 2026-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calory', '0002_dailysummary_deficiency_alter_dailysummary_healthy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20),
            preserve_default=False,
        ),
    ]
