# Generated by Django 6.0.1 on 2026-02-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calory', '0003_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='target',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
