# Generated by Django 6.0.1 on 2026-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calory', '0004_dailysummary_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='target',
            field=models.FloatField(default=0),
        ),
    ]
