# Generated by Django 6.0.1 on 2026-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calory', '0005_alter_dailysummary_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='meal_type',
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_grams',
            field=models.FloatField(default=100),
        ),
    ]
